field: 5e03956a-5dda-4844-b5df-8f39698eb0e1 # Nav Links
fieldLayouts:
  4c1aec01-7276-4e30-8d2f-365d8ec33ceb:
    tabs:
      -
        elements:
          -
            fieldUid: 91a5d6ea-7141-427c-b626-1980044ee3a7 # Link Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9f6248ff-d026-4286-ae6a-5b3a62b104f5 # Link Destination
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9f6248ff-d026-4286-ae6a-5b3a62b104f5: # Link Destination
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: ''
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select an Entry'
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  91a5d6ea-7141-427c-b626-1980044ee3a7: # Link Text
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: link
name: Link
sortOrder: 1
