contentColumnType: string
fieldGroup: e1348357-5508-43b0-a30b-d2ec3cd06eba # Common
handle: heroImage
instructions: ''
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:17271997-9dab-40bb-9bb8-fbc557f7e075' # Uploads
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:17271997-9dab-40bb-9bb8-fbc557f7e075' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:17271997-9dab-40bb-9bb8-fbc557f7e075' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
